kind: ConfigMap
apiVersion: v1
metadata:
  name: example-qm-web-configmap
  namespace: cp4i
  uid: 1cb1cd30-cc57-4095-9a20-fc44f1253c00
  resourceVersion: '1005819'
  creationTimestamp: '2024-03-20T10:46:13Z'
  labels:
    app.kubernetes.io/component: integration
    app.kubernetes.io/instance: orders
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: ibm-mq
    app.kubernetes.io/version: 9.3.4.0
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-03-20T11:43:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:mqwebexternal.xml': {}
          'f:mqwebuser.xml': {}
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
data:
  mqwebexternal.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <server>
        <featureManager>
            <feature>openidConnectClient-1.0</feature>
        </featureManager>
        <enterpriseApplication id="com.ibm.mq.console">
            <application-bnd>
                <security-role name="MQWebAdmin">
                    <group name="admins" access-id="group:integration/admin"/>
                    <group name="admins" access-id="group:integration/queuemanager-webadmin"/>
                    <group name="admins" access-id="group:integration/webadmin"/>
                </security-role>
                <security-role name="MQWebAdminRO">
                    <group name="readers" access-id="group:integration/queuemanager-webadminro"/>
                    <group name="readers" access-id="group:integration/webadminro"/>
                </security-role>
                <security-role name="MQWebUser">
                    <group name="users" access-id="group:integration/queuemanager-webuser"/>
                    <group name="users" access-id="group:integration/webuser"/>
                </security-role>
            </application-bnd>
        </enterpriseApplication>
        <authFilter id="integrationKeycloak">
            <webApp id="com.ibm.mq.console" name="com.ibm.mq.console" matchType="equals"/>
        </authFilter>
        <openidConnectClient id="mqclient"
            authFilterRef="integrationKeycloak"
            disableLtpaCookie="true"
            jwtAccessTokenRemoteValidation="require"
            clientId="${env.MQ_OIDC_CLIENT_ID}"
            clientSecret="${env.MQ_OIDC_CLIENT_SECRET}"
            scope="openid profile"
            signatureAlgorithm="RS256"
            groupIdentifier="effective-roles"
            userIdentifier="preferred_username"
            realmName="integration"
            discoveryEndpointUrl="${env.MQ_OIDC_DISCOVERY_ENDPOINT_URL}">
        </openidConnectClient>
        <jndiEntry jndiName="icp4iPlatformServicesUrl" value="${env.MQ_CP4I_SERVICES_URL}/v1"/>
        <jndiEntry jndiName="integrationKeycloakUrl" value="${env.MQ_KEYCLOAK_ENDPOINT_URL}"/>
    </server>
  mqwebuser.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <server>
        <featureManager>
            <feature>apiDiscovery-1.0</feature>
            <feature>appSecurity-2.0</feature>
            <feature>basicAuthenticationMQ-1.0</feature>
        </featureManager>

        <enterpriseApplication id="com.ibm.mq.rest">
        <application-bnd>
            <security-role name="MQWebAdmin">
                <group name="MQWebAdminGroup" realm="defaultRealm"/>
            </security-role>
            <security-role name="MQWebAdminRO">
                <user name="mqreader" realm="defaultRealm"/>
            </security-role>
            <security-role name="MQWebUser">
                <special-subject type="ALL_AUTHENTICATED_USERS"/>
            </security-role>
            <security-role name="MFTWebAdmin">
                <user name="mftadmin" realm="defaultRealm"/>
            </security-role>
            <security-role name="MFTWebAdminRO">
                <user name="mftreader" realm="defaultRealm"/>
            </security-role>
        </application-bnd>
    </enterpriseApplication>


    <basicRegistry id="basic" realm="defaultRealm">
    <user name="app1" password="{hash}ATAAAAAIGH/rX4J8t/JAAAAAIJyjgH3qpIZ115Lj1lWJ6ds7Pyw2T8ri5pfB+PFqPohV"/>
    <user name="mqadmin" password="{hash}ATAAAAAIGH/rX4J8t/JAAAAAIJyjgH3qpIZ115Lj1lWJ6ds7Pyw2T8ri5pfB+PFqPohV"/>
    <user name="mqreader" password="{hash}ATAAAAAIGH/rX4J8t/JAAAAAIJyjgH3qpIZ115Lj1lWJ6ds7Pyw2T8ri5pfB+PFqPohV"/>
        <group name="MQWebAdminGroup">
           <member name="mqadmin"/>
        </group>
        <group name="MQWebAdminROGroup">
           <member name="mqreader"/>
        </group>
    </basicRegistry>

      <variable name="httpHost" value="*"/>
      <variable name="managementMode" value="externallyprovisioned"/>

    </server>
